# -*- coding: utf-8 -*-
"""UPI_Fake_Detection

Automatically generated by Colab.

"""

# !pip install faker geopy

import pandas as pd
import numpy as np
import random
from faker import Faker
from geopy.geocoders import Nominatim
from datetime import datetime, timedelta
import time

import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta
import uuid

# Seed for reproducibility
Faker.seed(42)
random.seed(42)
np.random.seed(42)
fake = Faker('en_IN')

# Configuration
TOTAL_TXNS = 10000
FRAUD_PERCENT = 0.12
FRAUD_TXNS = int(TOTAL_TXNS * FRAUD_PERCENT)
NORMAL_TXNS = TOTAL_TXNS - FRAUD_TXNS

# Merchant category logic
CATEGORIES = ['groceries', 'fuel', 'ecommerce', 'food', 'utilities', 'travel', 'healthcare']
CATEGORY_WEIGHTS = [25, 10, 20, 20, 10, 10, 5]

CATEGORY_AMOUNTS = {
    'groceries': (50, 1000),
    'fuel': (100, 3000),
    'ecommerce': (200, 5000),
    'food': (100, 1500),
    'utilities': (200, 3000),
    'travel': (500, 10000),
    'healthcare': (300, 8000)
}

CITY_COORDS = {
    'Chennai': (13.0827, 80.2707),
    'Coimbatore': (11.0168, 76.9558),
    'Madurai': (9.9252, 78.1198),
    'Salem': (11.6643, 78.1460),
    'Trichy': (10.7905, 78.7047)
}

def generate_txn(index, base_time, fraud=False):
    category = random.choices(CATEGORIES, weights=CATEGORY_WEIGHTS, k=1)[0]
    amount = round(random.uniform(*CATEGORY_AMOUNTS[category]), 2)
    recipient_id = fake.email().split('@')[0] + "@upi"
    city = random.choice(list(CITY_COORDS.keys()))
    lat_jitter, lon_jitter = random.uniform(-0.01, 0.01), random.uniform(-0.01, 0.01)
    lat = CITY_COORDS[city][0] + lat_jitter
    lon = CITY_COORDS[city][1] + lon_jitter
    device_id = fake.uuid4()
    txn_time = base_time + timedelta(seconds=random.randint(60, 600))  # 1 to 10 min later
    txn_status = 'success'

    txn = {
        'transaction_id': str(uuid.uuid4()),
        'recipient_id': recipient_id,
        'amount': amount,
        'merchant_category': category,
        'device_id': device_id,
        'location': city,
        'latitude': round(lat, 6),
        'longitude': round(lon, 6),
        'time': txn_time,
        'txn_status': txn_status,
        'is_fraud': 0
    }

    if fraud:
        fraud_type = random.choice(['new_recipient', 'gps_spoof', 'odd_hour', 'high_amount'])
        txn['is_fraud'] = 1

        if fraud_type == 'new_recipient':
            txn['recipient_id'] = 'fraud_' + str(index) + "@upi"

        elif fraud_type == 'gps_spoof':
            txn['latitude'] = 28.6139  # Delhi coords
            txn['longitude'] = 77.2090
            txn['location'] = "Delhi"

        elif fraud_type == 'odd_hour':
            txn_time = txn_time.replace(hour=random.randint(1, 4))
            txn['time'] = txn_time

        elif fraud_type == 'high_amount':
            txn['amount'] = round(random.uniform(5000, 20000), 2)
            txn['merchant_category'] = 'groceries'

    return txn, txn['time']

# Dataset generation
print("🔁 Generating synthetic transactions...")
data = []
current_time = datetime.now() - timedelta(days=30)

# Normal transactions
for i in range(NORMAL_TXNS):
    txn, current_time = generate_txn(i, current_time, fraud=False)
    data.append(txn)

# Fraudulent transactions
for i in range(FRAUD_TXNS):
    txn, current_time = generate_txn(i + NORMAL_TXNS, current_time, fraud=True)
    data.append(txn)

# Create DataFrame and sort chronologically
df = pd.DataFrame(data)
df = df.sort_values(by='time').reset_index(drop=True)

# Compute time_since_last_txn (always positive)
df['time'] = pd.to_datetime(df['time'])
df['time_since_last_txn'] = df['time'].diff().fillna(pd.Timedelta(seconds=0)).dt.total_seconds()
df['time_since_last_txn'] = df['time_since_last_txn'].apply(lambda x: max(x, 1.0))

# Save
df.to_csv("upi_transactions.csv", index=False)
print("✅ upi_transactions.csv saved with 12% fraud, real-time-friendly timestamps.")

# Show sample
df.head()

# 📁 1. Import Libraries
import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler, LabelEncoder
import joblib

# 📂 2. Load Dataset
df = pd.read_csv("upi_transactions.csv")

# ✅ 3. Keep only successful transactions
df = df[df["txn_status"] == "success"].copy()

# 🧹 4. Drop columns not needed for unsupervised modeling
cols_to_drop = ["txn_status", "transaction_id", "time", "latitude", "longitude"]
df.drop(columns=cols_to_drop, errors="ignore", inplace=True)

# 💡 5. Drop is_fraud for unsupervised learning (optional)
if 'is_fraud' in df.columns:
    df.drop(columns=["is_fraud"], inplace=True)

# 🏷️ 6. Encode Categorical Columns
cat_cols = ['recipient_id', 'location', 'merchant_category', 'device_id']
label_encoders = {}

for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# 🧮 7. Scale Numeric Data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

# 💾 Save encoders and scaler
joblib.dump(scaler, "scaler.pkl")
for col, le in label_encoders.items():
    joblib.dump(le, f"{col}_encoder.pkl")

# 🌲 8. Train Isolation Forest
iso_model = IsolationForest(n_estimators=100, contamination=0.12, random_state=42)
iso_model.fit(X_scaled)
df["iso_score"] = iso_model.decision_function(X_scaled)
df["iso_anomaly"] = iso_model.predict(X_scaled)
df["iso_anomaly"] = df["iso_anomaly"].map({1: 0, -1: 1})  # 1 = fraud/anomaly

# 🔍 9. Train One-Class SVM
svm_model = OneClassSVM(kernel='rbf', gamma='scale', nu=0.12)
svm_model.fit(X_scaled)
df["svm_score"] = svm_model.decision_function(X_scaled)
df["svm_anomaly"] = svm_model.predict(X_scaled)
df["svm_anomaly"] = df["svm_anomaly"].map({1: 0, -1: 1})  # 1 = fraud/anomaly

# 💾 10. Save Models
joblib.dump(iso_model, "isolation_forest.pkl")
joblib.dump(svm_model, "one_class_svm.pkl")

# 📁 11. Save Scored Output
df.to_csv("scored_transactions_unsupervised.csv", index=False)
print("✅ Unsupervised scoring complete. Output saved.")

# !pip install faker

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# Set seed for reproducibility
np.random.seed(42)
random.seed(42)

# Configuration
NUM_ROWS = 3000
user_ids = [f"user_{i}" for i in range(1, 101)]  # 100 users

# Predefined options
transaction_modes = ["UPI_ID", "QR", "Phone Number", "Intent Link"]
transaction_types = ["P2P", "P2M", "Self Transfer"]
merchant_categories = [
    "Grocery",
    "Food & Restaurants",
    "Mobile Recharge",
    "Bills & Utilities",
    "Fuel",
    "Online Shopping",
    "Transportation",
    "Medical & Pharmacy"
]
upi_apps = ["GPay", "PhonePe", "Paytm", "BHIM"]
device_types = ["Mobile", "Desktop"]
states = ["Tamil Nadu", "Maharashtra", "Delhi", "Karnataka", "West Bengal"]
times_of_day = ["Morning", "Afternoon", "Evening", "Night"]

def random_time_of_day(ts):
    hour = ts.hour
    if 6 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

# Generate data
data = []
for i in range(NUM_ROWS):
    user = random.choice(user_ids)
    ts = datetime.now() - timedelta(days=random.randint(0, 30), hours=random.randint(0, 23), minutes=random.randint(0, 59))
    amount = round(np.random.uniform(5, 2000))
    txn_count_7 = random.randint(1, 20)
    avg_amt_30 = round(np.random.uniform(50, 1000))
    deviation = round((amount - avg_amt_30) / avg_amt_30)
    merchant = random.choice(merchant_categories)
    payee_repeat = random.randint(0, 10)
    new_payees_7 = random.randint(0, 5)
    repeat_vs_new = round(payee_repeat / (new_payees_7 + 1), 2)
    usual_mode = random.choice(transaction_modes)
    current_mode = random.choice(transaction_modes)

    row = {
        "Transaction_ID": f"TXN{i+1:05d}",
        "User_ID": user,
        "Timestamp": ts,
        "Amount": amount,
        "Transaction_Mode": current_mode,
        "Transaction_Type": random.choice(transaction_types),
        "Merchant_Category": merchant,
        "UPI_App": random.choice(upi_apps),
        "Location_State": random.choice(states),
        "Device_Type": random.choice(device_types),
        "Is_First_Time_Payee": random.choice([True, False]),
        "Days_Since_Last_Txn": random.randint(0, 15),
        "Txn_Count_Last_7_Days": txn_count_7,
        "Avg_Amt_Last_30_Days": avg_amt_30,
        "Amount_vs_Avg_Deviation": deviation,
        "Weekday_Weekend": "Weekend" if ts.weekday() >= 5 else "Weekday",
        "Time_Of_Day": random_time_of_day(ts),
        "Payee_Repetition_Count": payee_repeat,
        "Txn_Velocity_Per_Hour": round(txn_count_7 / random.uniform(1, 24), 2),
        "Amount_Velocity_Per_Day": round((txn_count_7 * avg_amt_30) / 7, 2),
        "Usual_Transaction_Mode": usual_mode,
        "Mode_Deviation": current_mode != usual_mode,
        "Merchant_Loyalty_Score": round(random.uniform(0.2, 0.9), 2),
        "New_Payees_Last_7_Days": new_payees_7,
        "Repeat_vs_New_Ratio": repeat_vs_new,
        "Is_Fraud": int(random.random() < 0.08)  # 8% fraud
    }
    data.append(row)

# Create DataFrame
df = pd.DataFrame(data)
df.head()

df.to_csv("upi_micro_transaction_dataset.csv", index=False)

#Load & Preprocess Dataset

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Load dataset
df = pd.read_csv("upi_micro_transaction_dataset.csv")

# Drop non-feature columns
X = df.drop(columns=["Transaction_ID", "User_ID", "Timestamp", "Is_Fraud"])

# Encode categorical columns
categorical_cols = X.select_dtypes(include=['object', 'bool']).columns
le = LabelEncoder()
for col in categorical_cols:
    X[col] = le.fit_transform(X[col].astype(str))

# Save scaled version for One-Class SVM
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

#Unsupervised Anomaly Detection

from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report

iso_model = IsolationForest(contamination=0.08, random_state=42)
iso_preds = iso_model.fit_predict(X)
# Map -1 to 1 (fraud), 1 to 0 (normal)
iso_preds = [1 if p == -1 else 0 for p in iso_preds]

print("Isolation Forest Results:")
print(classification_report(df["Is_Fraud"], iso_preds))

from sklearn.svm import OneClassSVM

svm_model = OneClassSVM(kernel="rbf", nu=0.08, gamma='auto')
svm_model.fit(X_scaled)
svm_preds = svm_model.predict(X_scaled)
# Map -1 to 1 (fraud), 1 to 0 (normal)
svm_preds = [1 if p == -1 else 0 for p in svm_preds]

print("One-Class SVM Results:")
print(classification_report(df["Is_Fraud"], svm_preds))

#Supervised ML(If Is_Fraud is available)

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import xgboost as xgb
import lightgbm as lgb

# Split data
y = df["Is_Fraud"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb_model.fit(X_train, y_train)
xgb_preds = xgb_model.predict(X_test)

print("XGBoost Results:")
print(classification_report(y_test, xgb_preds))

lgb_model = lgb.LGBMClassifier()
lgb_model.fit(X_train, y_train)
lgb_preds = lgb_model.predict(X_test)

print("LightGBM Results:")
print(classification_report(y_test, lgb_preds))

# SHAP Explainability (for XGBoost or LightGBM)
try:
    import shap
    explainer = shap.TreeExplainer(xgb_model)
    shap_values = explainer.shap_values(X_test)

    # Plot summary
    shap.summary_plot(shap_values, X_test, feature_names=X.columns)
except ImportError:
    print("⚠️ SHAP not installed. Skipping explainability plot.")

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# Set seed for reproducibility
np.random.seed(42)
random.seed(42)

# Configuration
NUM_ROWS = 3000
user_ids = [f"user_{i}" for i in range(1, 101)]  # 100 users

# Predefined options
transaction_modes = ["UPI_ID", "QR", "Phone Number", "Intent Link"]
transaction_types = ["P2P", "P2M", "Self Transfer"]
merchant_categories = [
    "Grocery", "Food & Restaurants", "Mobile Recharge", "Bills & Utilities",
    "Fuel", "Online Shopping", "Transportation", "Medical & Pharmacy"
]
upi_apps = ["GPay", "PhonePe", "Paytm", "BHIM"]
device_types = ["Mobile", "Desktop"]
states = ["Tamil Nadu", "Maharashtra", "Delhi", "Karnataka", "West Bengal"]

def random_time_of_day(ts):
    hour = ts.hour
    if 6 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

def create_fraud_pattern(base_row, fraud_type):
    """Create realistic fraud patterns based on research"""
    fraud_row = base_row.copy()

    if fraud_type == "velocity_fraud":
        # High velocity fraud: Multiple transactions in short time
        fraud_row["Txn_Count_Last_7_Days"] = random.randint(15, 25)  # Much higher than normal
        fraud_row["Txn_Velocity_Per_Hour"] = round(random.uniform(3.0, 8.0), 2)  # 3-8x normal
        fraud_row["New_Payees_Last_7_Days"] = random.randint(8, 15)  # Many new payees
        fraud_row["Days_Since_Last_Txn"] = random.randint(0, 1)  # Recent activity

    elif fraud_type == "amount_deviation":
        # Amount deviation fraud: Unusual spending patterns
        normal_avg = fraud_row["Avg_Amt_Last_30_Days"]
        fraud_row["Amount"] = round(normal_avg * random.uniform(3.0, 8.0))  # 3-8x normal amount
        fraud_row["Amount_vs_Avg_Deviation"] = round((fraud_row["Amount"] - normal_avg) / normal_avg, 2)

    elif fraud_type == "timing_fraud":
        # Odd timing fraud: Late night/early morning transactions
        fraud_hour = random.choice([1, 2, 3, 4, 23, 0])  # Late night/early morning
        fraud_date = datetime.now() - timedelta(
            days=random.randint(0, 30),
            hours=fraud_hour,
            minutes=random.randint(0, 59)
        )
        fraud_row["Timestamp"] = fraud_date
        fraud_row["Time_Of_Day"] = random_time_of_day(fraud_date)
        fraud_row["Weekday_Weekend"] = "Weekend" if fraud_date.weekday() >= 5 else "Weekday"

    elif fraud_type == "new_payee_fraud":
        # New payee fraud: First time transactions with suspicious patterns
        fraud_row["Is_First_Time_Payee"] = True
        fraud_row["Payee_Repetition_Count"] = 0
        fraud_row["New_Payees_Last_7_Days"] = random.randint(5, 12)  # Many new payees
        fraud_row["Repeat_vs_New_Ratio"] = 0.0  # Only new payees

    elif fraud_type == "mode_deviation":
        # Mode deviation fraud: Using unusual payment methods
        fraud_row["Mode_Deviation"] = True
        fraud_row["Transaction_Mode"] = "Intent Link"  # Less common mode
        fraud_row["Usual_Transaction_Mode"] = random.choice(["UPI_ID", "QR"])  # Different from current

    elif fraud_type == "loyalty_fraud":
        # Low loyalty fraud: Using many different merchants
        fraud_row["Merchant_Loyalty_Score"] = round(random.uniform(0.1, 0.3), 2)  # Very low loyalty
        fraud_row["New_Payees_Last_7_Days"] = random.randint(6, 12)

    return fraud_row

# Generate base dataset
print("Generating base dataset...")
data = []

for i in range(NUM_ROWS):
    user = random.choice(user_ids)
    ts = datetime.now() - timedelta(
        days=random.randint(0, 30),
        hours=random.randint(0, 23),
        minutes=random.randint(0, 59)
    )

    # Generate normal transaction parameters
    txn_count_7 = random.randint(1, 12)  # Normal range
    avg_amt_30 = round(random.uniform(200, 800))  # Normal spending
    amount = round(random.uniform(avg_amt_30 * 0.5, avg_amt_30 * 1.5))  # Normal variation
    deviation = round((amount - avg_amt_30) / avg_amt_30, 2)

    payee_repeat = random.randint(1, 8)
    new_payees_7 = random.randint(0, 3)  # Normal new payees
    repeat_vs_new = round(payee_repeat / (new_payees_7 + 1), 2)

    usual_mode = random.choice(transaction_modes)
    current_mode = usual_mode if random.random() < 0.8 else random.choice(transaction_modes)

    base_row = {
        "Transaction_ID": f"TXN{i+1:05d}",
        "User_ID": user,
        "Timestamp": ts,
        "Amount": amount,
        "Transaction_Mode": current_mode,
        "Transaction_Type": random.choice(transaction_types),
        "Merchant_Category": random.choice(merchant_categories),
        "UPI_App": random.choice(upi_apps),
        "Location_State": random.choice(states),
        "Device_Type": random.choice(device_types),
        "Is_First_Time_Payee": random.choice([True, False]),
        "Days_Since_Last_Txn": random.randint(1, 10),  # Normal frequency
        "Txn_Count_Last_7_Days": txn_count_7,
        "Avg_Amt_Last_30_Days": avg_amt_30,
        "Amount_vs_Avg_Deviation": deviation,
        "Weekday_Weekend": "Weekend" if ts.weekday() >= 5 else "Weekday",
        "Time_Of_Day": random_time_of_day(ts),
        "Payee_Repetition_Count": payee_repeat,
        "Txn_Velocity_Per_Hour": round(txn_count_7 / random.uniform(24, 168), 2),  # Normal velocity
        "Amount_Velocity_Per_Day": round((txn_count_7 * avg_amt_30) / 7, 2),
        "Usual_Transaction_Mode": usual_mode,
        "Mode_Deviation": current_mode != usual_mode,
        "Merchant_Loyalty_Score": round(random.uniform(0.4, 0.9), 2),  # Normal loyalty
        "New_Payees_Last_7_Days": new_payees_7,
        "Repeat_vs_New_Ratio": repeat_vs_new,
        "Is_Fraud": 0  # Initialize as normal
    }

    data.append(base_row)

# Convert to DataFrame for easier manipulation
df_base = pd.DataFrame(data)

print(f"Generated {len(df_base)} base transactions")

# ===== INJECT REALISTIC FRAUD PATTERNS =====
print("Injecting fraud patterns...")

fraud_types = ["velocity_fraud", "amount_deviation", "timing_fraud",
               "new_payee_fraud", "mode_deviation", "loyalty_fraud"]

# Select random indices for fraud injection (8% fraud rate)
num_frauds = int(len(df_base) * 0.08)
fraud_indices = random.sample(range(len(df_base)), num_frauds)

print(f"Injecting {num_frauds} fraud transactions...")

fraud_pattern_counts = {pattern: 0 for pattern in fraud_types}

for idx in fraud_indices:
    # Randomly select fraud type
    fraud_type = random.choice(fraud_types)
    fraud_pattern_counts[fraud_type] += 1

    # Create fraud pattern
    original_row = df_base.iloc[idx].to_dict()
    fraud_row = create_fraud_pattern(original_row, fraud_type)
    fraud_row["Is_Fraud"] = 1

    # Update the row in dataframe
    for col, val in fraud_row.items():
        df_base.at[idx, col] = val

print("Fraud pattern distribution:")
for pattern, count in fraud_pattern_counts.items():
    print(f"  {pattern}: {count} transactions")

# ===== FINAL VERIFICATION =====
print("\n=== FRAUD INJECTION VERIFICATION ===")
fraud_df = df_base[df_base['Is_Fraud'] == 1]
normal_df = df_base[df_base['Is_Fraud'] == 0]

print(f"Total transactions: {len(df_base)}")
print(f"Normal transactions: {len(normal_df)} ({len(normal_df)/len(df_base)*100:.1f}%)")
print(f"Fraud transactions: {len(fraud_df)} ({len(fraud_df)/len(df_base)*100:.1f}%)")

print("\n=== FEATURE DIFFERENCES (Should be significant now) ===")
comparison_features = ['Amount', 'Txn_Count_Last_7_Days', 'Amount_vs_Avg_Deviation',
                      'Txn_Velocity_Per_Hour', 'New_Payees_Last_7_Days', 'Merchant_Loyalty_Score']

for feature in comparison_features:
    normal_mean = normal_df[feature].mean()
    fraud_mean = fraud_df[feature].mean()
    difference = abs(fraud_mean - normal_mean)
    pct_diff = (difference / normal_mean) * 100 if normal_mean != 0 else 0
    print(f"{feature:25} | Normal: {normal_mean:8.2f} | Fraud: {fraud_mean:8.2f} | Diff: {difference:8.2f} ({pct_diff:.1f}%)")

# Save the improved dataset
df_base.to_csv("upi_micro_transaction_dataset_improved.csv", index=False)
print(f"\nImproved dataset saved as 'upi_micro_transaction_dataset_improved.csv'")

# ===== NOW RUN YOUR MACHINE LEARNING PIPELINE =====
print("\n" + "="*50)
print("READY TO RUN MACHINE LEARNING PIPELINE")
print("="*50)

# Prepare data for ML (same as your existing preprocessing)
df = df_base.copy()

# Drop non-feature columns
X = df.drop(columns=["Transaction_ID", "User_ID", "Timestamp", "Is_Fraud"])

# Encode categorical columns
from sklearn.preprocessing import LabelEncoder, StandardScaler

categorical_cols = X.select_dtypes(include=['object', 'bool']).columns
le = LabelEncoder()
for col in categorical_cols:
    X[col] = le.fit_transform(X[col].astype(str))

# Save scaled version
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Data preprocessing complete. Features ready for ML models.")
print(f"Feature matrix shape: {X.shape}")
print(f"Target distribution: Normal={sum(df['Is_Fraud']==0)}, Fraud={sum(df['Is_Fraud']==1)}")

# Continue from your existing code...
# Your data generation and preprocessing code is already done

# ===== COMPLETE FRAUD DETECTION PIPELINE =====

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import IsolationForest
from sklearn.svm import OneClassSVM
from sklearn.model_selection import train_test_split
from sklearn.metrics import (classification_report, confusion_matrix,
                           roc_auc_score, roc_curve, precision_recall_curve)
from imblearn.over_sampling import SMOTE
import xgboost as xgb
import lightgbm as lgb
try:
    import shap
except ImportError:
    print("⚠️ SHAP not installed. SHAP analysis will be skipped.")
import warnings
warnings.filterwarnings('ignore')

# Set up plotting style
plt.style.use('default')
sns.set_palette("husl")

print("=== UPI FRAUD DETECTION ANALYSIS ===")
print(f"Dataset shape: {df.shape}")
print(f"Feature columns: {len(X.columns)}")

# ===== 1. DATA ANALYSIS =====
def analyze_dataset(df, X):
    """Comprehensive dataset analysis"""
    print("\n=== DATASET ANALYSIS ===")

    # Fraud distribution
    fraud_counts = df['Is_Fraud'].value_counts()
    fraud_rate = fraud_counts[1] / len(df) * 100

    print(f"Normal transactions: {fraud_counts[0]} ({100-fraud_rate:.1f}%)")
    print(f"Fraud transactions: {fraud_counts[1]} ({fraud_rate:.1f}%)")

    # Feature statistics for fraud vs normal
    print("\n=== KEY FEATURE DIFFERENCES (Fraud vs Normal) ===")
    numeric_features = ['Amount', 'Txn_Count_Last_7_Days', 'Amount_vs_Avg_Deviation',
                       'Days_Since_Last_Txn', 'Txn_Velocity_Per_Hour']

    for feature in numeric_features:
        if feature in df.columns:
            normal_mean = df[df['Is_Fraud']==0][feature].mean()
            fraud_mean = df[df['Is_Fraud']==1][feature].mean()
            difference = abs(fraud_mean - normal_mean)
            print(f"{feature:25} | Normal: {normal_mean:8.2f} | Fraud: {fraud_mean:8.2f} | Diff: {difference:8.2f}")

    # Visualize fraud distribution
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))

    # Fraud distribution pie chart
    axes[0,0].pie([fraud_counts[0], fraud_counts[1]],
                  labels=['Normal', 'Fraud'],
                  autopct='%1.1f%%',
                  colors=['lightblue', 'salmon'])
    axes[0,0].set_title('Transaction Distribution')

    # Amount distribution
    axes[0,1].hist(df[df['Is_Fraud']==0]['Amount'], bins=30, alpha=0.7, label='Normal', color='blue')
    axes[0,1].hist(df[df['Is_Fraud']==1]['Amount'], bins=30, alpha=0.7, label='Fraud', color='red')
    axes[0,1].set_xlabel('Amount')
    axes[0,1].set_ylabel('Frequency')
    axes[0,1].set_title('Amount Distribution')
    axes[0,1].legend()

    # Transaction count distribution
    axes[1,0].hist(df[df['Is_Fraud']==0]['Txn_Count_Last_7_Days'], bins=20, alpha=0.7, label='Normal', color='blue')
    axes[1,0].hist(df[df['Is_Fraud']==1]['Txn_Count_Last_7_Days'], bins=20, alpha=0.7, label='Fraud', color='red')
    axes[1,0].set_xlabel('Transactions (Last 7 Days)')
    axes[1,0].set_ylabel('Frequency')
    axes[1,0].set_title('Transaction Frequency Distribution')
    axes[1,0].legend()

    # Time of day analysis
    time_fraud = df.groupby(['Time_Of_Day', 'Is_Fraud']).size().unstack(fill_value=0)
    time_fraud_pct = time_fraud.div(time_fraud.sum(axis=1), axis=0) * 100
    time_fraud_pct[1].plot(kind='bar', ax=axes[1,1], color='salmon')
    axes[1,1].set_title('Fraud Rate by Time of Day')
    axes[1,1].set_ylabel('Fraud Percentage')
    axes[1,1].tick_params(axis='x', rotation=45)

    plt.tight_layout()
    plt.show()

    return fraud_rate

# ===== 2. IMPROVED ISOLATION FOREST =====
def run_isolation_forest(X, X_scaled, y, contamination_rate):
    """Run Isolation Forest with proper evaluation"""
    print("\n=== ISOLATION FOREST ANALYSIS ===")

    # Model with better parameters
    iso_model = IsolationForest(
        contamination=contamination_rate/100,  # Convert percentage to decimal
        random_state=42,
        n_estimators=200,
        max_samples='auto',
        bootstrap=False
    )

    # Fit and predict
    iso_model.fit(X_scaled)
    iso_scores = iso_model.decision_function(X_scaled)
    iso_preds = iso_model.predict(X_scaled)

    # Convert predictions: -1 (anomaly) -> 1 (fraud), 1 (normal) -> 0
    iso_preds_binary = [1 if p == -1 else 0 for p in iso_preds]

    # Evaluation
    print("Isolation Forest Results:")
    print(classification_report(y, iso_preds_binary))

    # Confusion Matrix
    cm = confusion_matrix(y, iso_preds_binary)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Normal', 'Fraud'],
                yticklabels=['Normal', 'Fraud'])
    plt.title('Isolation Forest - Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

    # ROC Curve
    if len(np.unique(y)) > 1:
        fpr, tpr, _ = roc_curve(y, -iso_scores)  # Negative because lower scores = more anomalous
        auc_score = roc_auc_score(y, -iso_scores)

        plt.figure(figsize=(8, 6))
        plt.plot(fpr, tpr, label=f'Isolation Forest (AUC = {auc_score:.3f})')
        plt.plot([0, 1], [0, 1], 'k--', label='Random')
        plt.xlabel('False Positive Rate')
        plt.ylabel('True Positive Rate')
        plt.title('ROC Curve - Isolation Forest')
        plt.legend()
        plt.grid(True)
        plt.show()

        print(f"AUC-ROC Score: {auc_score:.3f}")

    return iso_model, iso_preds_binary, iso_scores

# ===== 3. IMPROVED ONE-CLASS SVM =====
def run_one_class_svm(X_scaled, y, contamination_rate):
    """Run One-Class SVM with proper evaluation"""
    print("\n=== ONE-CLASS SVM ANALYSIS ===")

    # Model with better parameters
    svm_model = OneClassSVM(
        kernel="rbf",
        nu=contamination_rate/100,  # Convert percentage to decimal
        gamma='scale'
    )

    # Fit and predict
    svm_model.fit(X_scaled)
    svm_scores = svm_model.decision_function(X_scaled)
    svm_preds = svm_model.predict(X_scaled)

    # Convert predictions
    svm_preds_binary = [1 if p == -1 else 0 for p in svm_preds]

    # Evaluation
    print("One-Class SVM Results:")
    print(classification_report(y, svm_preds_binary))

    # Confusion Matrix
    cm = confusion_matrix(y, svm_preds_binary)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Greens',
                xticklabels=['Normal', 'Fraud'],
                yticklabels=['Normal', 'Fraud'])
    plt.title('One-Class SVM - Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

    return svm_model, svm_preds_binary, svm_scores

# ===== 4. IMPROVED SUPERVISED MODELS =====
def run_supervised_models(X, y):
    """Run supervised models with proper handling of imbalanced data"""
    print("\n=== SUPERVISED MODELS ANALYSIS ===")

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )

    print(f"Training set: {len(X_train)} samples ({y_train.sum()} fraud)")
    print(f"Test set: {len(X_test)} samples ({y_test.sum()} fraud)")

    # Scale features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    results = {}

    # === XGBoost with Class Balancing ===
    print("\n--- XGBoost with Class Weights ---")
    scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

    xgb_model = xgb.XGBClassifier(
        use_label_encoder=False,
        eval_metric='auc',
        scale_pos_weight=scale_pos_weight,
        max_depth=6,
        n_estimators=300,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42
    )

    xgb_model.fit(X_train_scaled, y_train)
    xgb_preds = xgb_model.predict(X_test_scaled)
    xgb_proba = xgb_model.predict_proba(X_test_scaled)[:, 1]

    print("XGBoost Results:")
    print(classification_report(y_test, xgb_preds))

    results['XGBoost'] = {
        'model': xgb_model,
        'predictions': xgb_preds,
        'probabilities': xgb_proba,
        'y_test': y_test
    }

    # === LightGBM with Class Balancing ===
    print("\n--- LightGBM with Class Balancing ---")
    lgb_model = lgb.LGBMClassifier(
        is_unbalance=True,
        n_estimators=300,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        verbose=-1
    )

    lgb_model.fit(X_train_scaled, y_train)
    lgb_preds = lgb_model.predict(X_test_scaled)
    lgb_proba = lgb_model.predict_proba(X_test_scaled)[:, 1]

    print("LightGBM Results:")
    print(classification_report(y_test, lgb_preds))

    results['LightGBM'] = {
        'model': lgb_model,
        'predictions': lgb_preds,
        'probabilities': lgb_proba,
        'y_test': y_test
    }

    # === SMOTE + XGBoost ===
    print("\n--- SMOTE + XGBoost ---")
    smote = SMOTE(random_state=42)
    X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

    print(f"After SMOTE: Normal={sum(y_train_smote==0)}, Fraud={sum(y_train_smote==1)}")

    xgb_smote = xgb.XGBClassifier(
        use_label_encoder=False,
        eval_metric='auc',
        max_depth=6,
        n_estimators=300,
        learning_rate=0.1,
        random_state=42
    )

    xgb_smote.fit(X_train_smote, y_train_smote)
    xgb_smote_preds = xgb_smote.predict(X_test_scaled)
    xgb_smote_proba = xgb_smote.predict_proba(X_test_scaled)[:, 1]

    print("SMOTE + XGBoost Results:")
    print(classification_report(y_test, xgb_smote_preds))

    results['XGBoost_SMOTE'] = {
        'model': xgb_smote,
        'predictions': xgb_smote_preds,
        'probabilities': xgb_smote_proba,
        'y_test': y_test
    }

    return results, X_test_scaled

# ===== 5. MODEL COMPARISON =====
def compare_models(results):
    """Compare all supervised models"""
    print("\n=== MODEL COMPARISON ===")

    comparison_data = []

    for model_name, result in results.items():
        y_true = result['y_test']
        y_pred = result['predictions']
        y_proba = result['probabilities']

        # Get classification report as dict
        report = classification_report(y_true, y_pred, output_dict=True)

        # Calculate AUC if possible
        try:
            auc_score = roc_auc_score(y_true, y_proba)
        except:
            auc_score = 0

        comparison_data.append({
            'Model': model_name,
            'Accuracy': report['accuracy'],
            'Fraud_Precision': report.get('1', {}).get('precision', 0),
            'Fraud_Recall': report.get('1', {}).get('recall', 0),
            'Fraud_F1': report.get('1', {}).get('f1-score', 0),
            'AUC_ROC': auc_score
        })

    comparison_df = pd.DataFrame(comparison_data)
    print(comparison_df.round(3))

    # Plot comparison
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))

    # Fraud Precision
    axes[0,0].bar(comparison_df['Model'], comparison_df['Fraud_Precision'])
    axes[0,0].set_title('Fraud Detection Precision')
    axes[0,0].set_ylabel('Precision')
    axes[0,0].tick_params(axis='x', rotation=45)

    # Fraud Recall
    axes[0,1].bar(comparison_df['Model'], comparison_df['Fraud_Recall'])
    axes[0,1].set_title('Fraud Detection Recall')
    axes[0,1].set_ylabel('Recall')
    axes[0,1].tick_params(axis='x', rotation=45)

    # F1 Score
    axes[1,0].bar(comparison_df['Model'], comparison_df['Fraud_F1'])
    axes[1,0].set_title('Fraud Detection F1-Score')
    axes[1,0].set_ylabel('F1-Score')
    axes[1,0].tick_params(axis='x', rotation=45)

    # AUC-ROC
    axes[1,1].bar(comparison_df['Model'], comparison_df['AUC_ROC'])
    axes[1,1].set_title('AUC-ROC Score')
    axes[1,1].set_ylabel('AUC-ROC')
    axes[1,1].tick_params(axis='x', rotation=45)

    plt.tight_layout()
    plt.show()

    return comparison_df

# ===== 6. SHAP ANALYSIS =====
def run_shap_analysis(model, X_test, feature_names):
    """Run SHAP analysis for model interpretability"""
    print("\n=== SHAP INTERPRETABILITY ANALYSIS ===")

    # Create explainer
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_test)

    # Summary plot
    plt.figure(figsize=(12, 8))
    shap.summary_plot(shap_values, X_test, feature_names=feature_names, show=False)
    plt.title("SHAP Feature Importance Summary")
    plt.tight_layout()
    plt.show()

    # Feature importance ranking
    feature_importance = np.abs(shap_values).mean(0)
    importance_df = pd.DataFrame({
        'Feature': feature_names,
        'Importance': feature_importance
    }).sort_values('Importance', ascending=False)

    print("\nTop 10 Most Important Features for Fraud Detection:")
    print(importance_df.head(10))

    # Plot top features
    plt.figure(figsize=(10, 6))
    top_features = importance_df.head(10)
    plt.barh(range(len(top_features)), top_features['Importance'])
    plt.yticks(range(len(top_features)), top_features['Feature'])
    plt.xlabel('SHAP Importance')
    plt.title('Top 10 Features for Fraud Detection')
    plt.gca().invert_yaxis()
    plt.tight_layout()
    plt.show()

    return shap_values, importance_df

# ===== MAIN EXECUTION =====
print("Starting comprehensive fraud detection analysis...")

# 1. Analyze dataset
fraud_rate = analyze_dataset(df, X)

# 2. Run Isolation Forest
iso_model, iso_preds, iso_scores = run_isolation_forest(X, X_scaled, df['Is_Fraud'], fraud_rate)

# 3. Run One-Class SVM
svm_model, svm_preds, svm_scores = run_one_class_svm(X_scaled, df['Is_Fraud'], fraud_rate)

# 4. Run supervised models
supervised_results, X_test_scaled = run_supervised_models(X, df['Is_Fraud'])

# 5. Compare models
comparison_df = compare_models(supervised_results)

# 6. SHAP analysis on best model
best_model_name = comparison_df.loc[comparison_df['Fraud_F1'].idxmax(), 'Model']
best_model = supervised_results[best_model_name]['model']

print(f"\nRunning SHAP analysis on best model: {best_model_name}")
shap_values, feature_importance = run_shap_analysis(best_model, X_test_scaled, X.columns)

print("\n=== ANALYSIS COMPLETE ===")
print("Key Findings:")
print(f"1. Dataset has {fraud_rate:.1f}% fraud rate")
print(f"2. Best performing model: {best_model_name}")
print(f"3. Best fraud F1-score: {comparison_df['Fraud_F1'].max():.3f}")
print(f"4. Most important feature: {feature_importance.iloc[0]['Feature']}")



### UPI Fake Screenshot Detection (Colab Notebook)
# Save this file as `upi_fake_screenshot_detection.py` or copy into a Colab notebook cell-by-cell.

# 1. Install and Imports

import os
import random
import cv2
import numpy as np
from PIL import Image
try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
except ImportError:
    print("⚠️ Torch not installed. CNN detection will be skipped.")
from torch.utils.data import Dataset, DataLoader, random_split
from torchvision import transforms, models

# 2. Directory Setup
# In Colab, run:
# !mkdir -p ./data/real
# !mkdir -p ./data/fake
# Upload your REAL screenshots into `./data/real`

# 3. Fake Screenshot Generation

def generate_fake_images(real_dir, fake_dir, variants_per_image=5):
    os.makedirs(fake_dir, exist_ok=True)
    for fname in os.listdir(real_dir):
        img_path = os.path.join(real_dir, fname)
        img = cv2.imread(img_path)
        h, w = img.shape[:2]
        for i in range(variants_per_image):
            fake = img.copy()
            # Safe hue shift to avoid OverflowError
            hsv = cv2.cvtColor(fake, cv2.COLOR_BGR2HSV)
            hue_shift = random.randint(-10, 10)

            # Convert hue channel to int16 for safe addition, then back to uint8
            hue = hsv[:, :, 0].astype(np.int16)
            hue = (hue + hue_shift) % 180
            hsv[:, :, 0] = hue.astype(np.uint8)

            fake = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)

            # Gaussian noise
            noise = np.random.normal(0, 5, fake.shape).astype(np.uint8)
            fake = cv2.add(fake, noise)
            # Random rotation
            angle = random.uniform(-3, 3)
            M = cv2.getRotationMatrix2D((w/2, h/2), angle, 1)
            fake = cv2.warpAffine(fake, M, (w, h), borderMode=cv2.BORDER_REFLECT)
            # Save
            out_fname = f"{os.path.splitext(fname)[0]}_fake_{i}.jpg"
            cv2.imwrite(os.path.join(fake_dir, out_fname), fake)

# Example usage (run after uploading real images):
generate_fake_images('./data/real', './data/fake', variants_per_image=5)

# 4. Dataset Definition
class UPIScreenshotDataset(Dataset):
    def __init__(self, real_dir, fake_dir, transform=None):
        self.samples = []
        for f in os.listdir(real_dir):
            self.samples.append((os.path.join(real_dir, f), 0))  # label 0: real
        for f in os.listdir(fake_dir):
            self.samples.append((os.path.join(fake_dir, f), 1))  # label 1: fake
        self.transform = transform

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        path, label = self.samples[idx]
        img = Image.open(path).convert('RGB')
        if self.transform:
            img = self.transform(img)
        return img, label

# 5. Transforms & DataLoader
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
])

dataset = UPIScreenshotDataset('./data/real', './data/fake', transform)
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_ds, val_ds = random_split(dataset, [train_size, val_size])
train_loader = DataLoader(train_ds, batch_size=16, shuffle=True)
val_loader = DataLoader(val_ds, batch_size=16)

# 6. Model Definition
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = models.mobilenet_v3_small(pretrained=True)
# Replace classifier head
in_features = model.classifier[0].in_features
model.classifier = nn.Sequential(
    nn.Linear(in_features, 128),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(128, 1),
    nn.Sigmoid()
)
model = model.to(device)

# 7. Training Setup
criterion = nn.BCELoss()
optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-5)

# 8. Training & Evaluation Functions

def train_one_epoch():
    model.train()
    running_loss = 0
    for imgs, labels in train_loader:
        imgs, labels = imgs.to(device), labels.float().to(device)
        optimizer.zero_grad()
        outputs = model(imgs).squeeze()
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    return running_loss / len(train_loader)


def evaluate(loader):
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for imgs, labels in loader:
            imgs, labels = imgs.to(device), labels.to(device)
            preds = (model(imgs).squeeze() > 0.5).long()
            correct += (preds == labels).sum().item()
            total += labels.size(0)
    return correct / total

# 9. Run Training Loop
num_epochs = 10
for epoch in range(1, num_epochs + 1):
    train_loss = train_one_epoch()
    val_acc = evaluate(val_loader)
    print(f"Epoch {epoch}/{num_epochs} - Loss: {train_loss:.4f}, Val Acc: {val_acc:.4f}")

# 10. Save Model
os.makedirs('./model', exist_ok=True)
torch.save(model.state_dict(), './model/upi_fake_detector.pth')
print("Model saved to ./model/upi_fake_detector.pth")

# 11. Inference Example
img = Image.open('./data/test/example.jpg').convert('RGB')
img = transform(img).unsqueeze(0).to(device)
with torch.no_grad():
    pred = (model(img).item() > 0.5)

print('Fake' if pred else 'Real')

# !pip install torch torchvision pillow opencv-python

# !mkdir -p ./data/real
# !mkdir -p ./data/fake
# !mkdir -p ./data/test

# Step 1: Restart & cleanly install PyTorch and torchvision
# !pip uninstall -y torch torchvision torchaudio
# !pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

# !pip install pytesseract

# =======================
# UPI Fake Screenshot Hybrid Detector
# =======================
# Copy this entire block into Colab (or save as upi_fake_hybrid_detector.py).
# Make sure you run the Colab Setup cell (above) first.

# 1. Imports & Setup
import os
import random
import re
import cv2
import numpy as np
try:
    import pytesseract
except ImportError:
    pass

try:
    import easyocr
except ImportError:
    pass

try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from torch.utils.data import Dataset, DataLoader, random_split
    from torchvision import transforms, models
except ImportError:
    print("⚠️ Torch not installed.")

# Set random seeds for reproducibility
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

# 2. Paths & Directories
REAL_DIR   = './data/real'    # Place your genuine UPI screenshots here
FAKE_DIR   = './data/fake'    # Synthetic fakes will be generated here
TEST_DIR   = './data/test'    # Put held-out real/fake images here for inference
MODEL_DIR  = './model'        # Where the trained model weights will be saved

os.makedirs(REAL_DIR, exist_ok=True)
os.makedirs(FAKE_DIR, exist_ok=True)
os.makedirs(TEST_DIR, exist_ok=True)
os.makedirs(MODEL_DIR, exist_ok=True)

# 3.  Fake Screenshot Generation (Visual Tampering)
def generate_fake_images(real_dir, fake_dir, variants_per_image=5):
    """
    For every image in real_dir, create 'variants_per_image' fakes by:
      - Hue shift
      - Gaussian noise
      - Small rotation
    Save to fake_dir.
    """
    os.makedirs(fake_dir, exist_ok=True)
    for fname in os.listdir(real_dir):
        img_path = os.path.join(real_dir, fname)
        img = cv2.imread(img_path)
        if img is None:
            continue
        h, w = img.shape[:2]
        base_name, ext = os.path.splitext(fname)
        for i in range(variants_per_image):
            fake = img.copy()

            # ---- Hue Shift (safe) ----
            hsv = cv2.cvtColor(fake, cv2.COLOR_BGR2HSV)
            hue_shift = random.randint(-10, 10)
            hue = hsv[:, :, 0].astype(np.int16)
            hue = (hue + hue_shift) % 180
            hsv[:, :, 0] = hue.astype(np.uint8)
            fake = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)

            # ---- Gaussian Noise ----
            noise = np.random.normal(0, 5, fake.shape).astype(np.uint8)
            fake = cv2.add(fake, noise)

            # ---- Small Rotation ----
            angle = random.uniform(-3, 3)
            M = cv2.getRotationMatrix2D((w/2, h/2), angle, 1)
            fake = cv2.warpAffine(fake, M, (w, h), borderMode=cv2.BORDER_REFLECT)

            out_fname = f"{base_name}_fake_{i}.jpg"
            cv2.imwrite(os.path.join(fake_dir, out_fname), fake)

# Example usage: run after you have uploaded real images into REAL_DIR
# generate_fake_images(REAL_DIR, FAKE_DIR, variants_per_image=5)

# 4. Dataset Definition (Visual-Only)
class UPIScreenshotDataset(Dataset):
    def __init__(self, real_dir, fake_dir, transform=None):
        self.samples = []
        for f in os.listdir(real_dir):
            path = os.path.join(real_dir, f)
            self.samples.append((path, 0))  # 0 = real
        for f in os.listdir(fake_dir):
            path = os.path.join(fake_dir, f)
            self.samples.append((path, 1))  # 1 = fake
        self.transform = transform

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        path, label = self.samples[idx]
        img = Image.open(path).convert('RGB')
        if self.transform:
            img = self.transform(img)
        return img, label

# 5. Transforms & DataLoader Setup
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2),
    transforms.ToTensor(),
])

# Instantiate dataset (after generating fakes)
dataset = UPIScreenshotDataset(REAL_DIR, FAKE_DIR, transform=transform)
train_size = int(0.8 * len(dataset))
val_size   = len(dataset) - train_size
train_ds, val_ds = random_split(dataset, [train_size, val_size])
train_loader = DataLoader(train_ds, batch_size=16, shuffle=True)
val_loader   = DataLoader(val_ds, batch_size=16)

# 6. Model Definition (MobileNetV3-Small)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = models.mobilenet_v3_small(pretrained=True)
in_features = model.classifier[0].in_features
model.classifier = nn.Sequential(
    nn.Linear(in_features, 128),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(128, 1),
    nn.Sigmoid()
)
model = model.to(device)

# 7. Training Setup
criterion = nn.BCELoss()
optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-5)

# 8. Training & Evaluation Functions
def train_one_epoch():
    model.train()
    running_loss = 0.0
    for imgs, labels in train_loader:
        imgs, labels = imgs.to(device), labels.float().to(device)
        optimizer.zero_grad()
        outputs = model(imgs).squeeze()
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    return running_loss / len(train_loader)

def evaluate(loader):
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for imgs, labels in loader:
            imgs, labels = imgs.to(device), labels.to(device)
            preds = (model(imgs).squeeze() > 0.5).long()
            correct += (preds == labels).sum().item()
            total += labels.size(0)
    return correct / total

# 9. Train the CNN
num_epochs = 10
for epoch in range(1, num_epochs + 1):
    train_loss = train_one_epoch()
    val_acc    = evaluate(val_loader)
    print(f"Epoch {epoch}/{num_epochs} — Loss: {train_loss:.4f}, Val Acc: {val_acc:.4f}")

# 10. Save the CNN Weights
torch.save(model.state_dict(), os.path.join(MODEL_DIR, 'upi_fake_detector_cnn.pth'))
print("✅ CNN model saved to", os.path.join(MODEL_DIR, 'upi_fake_detector_cnn.pth'))

# 11. OCR + Rule‐Based Field Extraction

# 11.1. Tesseract Configuration
pytesseract.pytesseract.tesseract_cmd = '/usr/bin/tesseract'

def ocr_extract_fields(image_path):
    """
    Given an image path (UPI screenshot), run OCR and extract:
      - amount (₹ or Rs followed by digits)
      - upi_id    (pattern: \w+@\w+)
      - txn_id    (alphanumeric string of length 8–30)
      - date/time (DD/MM/YYYY or similar)
    Returns a dict: {'amount': str or None, 'upi_id': str or None,
                     'txn_id': str or None, 'date': str or None}
    """
    img = cv2.imread(image_path)
    if img is None:
        return dict(amount=None, upi_id=None, txn_id=None, date=None)

    # Preprocess for OCR: grayscale + threshold
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.medianBlur(gray, 3)
    _, thresh = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    # Invert if needed
    thresh = cv2.bitwise_not(thresh)

    # OCR config: LSTM-only engine
    config = '--oem 1 --psm 6'
    text = pytesseract.image_to_string(thresh, config=config)

    # Patterns
    amount_pattern = re.compile(r'₹\s*\d{1,7}(?:,\d{3})*(?:\.\d{1,2})?|\bRs\.?\s*\d{1,7}(?:,\d{3})*(?:\.\d{1,2})?\b')
    upi_pattern    = re.compile(r'\b[\w\.]+@[\w\.]+\b')
    txn_pattern    = re.compile(r'\b[A-Za-z0-9]{8,30}\b')
    date_pattern   = re.compile(r'\b(?:\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4})\b')

    amount = None; upi_id = None; txn_id = None; date = None

    for line in text.split('\n'):
        if amount is None:
            m = amount_pattern.search(line)
            if m: amount = m.group(0).replace(' ', '').replace('Rs.', '₹')
        if upi_id is None:
            m = upi_pattern.search(line)
            if m: upi_id = m.group(0)
        if txn_id is None:
            m = txn_pattern.search(line)
            if m: txn_id = m.group(0)
        if date is None:
            m = date_pattern.search(line)
            if m: date = m.group(0)

    return dict(amount=amount, upi_id=upi_id, txn_id=txn_id, date=date)

# 11. OCR + Rule‐Based Field Extraction (Improved)

# Attempt to import EasyOCR; if missing, fall back to Tesseract
try:
    import easyocr
    _USE_EASYOCR = True
    # Initialize EasyOCR reader for English (en) only
    _EASYOCR_READER = easyocr.Reader(['en'], gpu=torch.cuda.is_available())
except ImportError:
    _USE_EASYOCR = False
    pytesseract.pytesseract.tesseract_cmd = '/usr/bin/tesseract'

def ocr_extract_fields(image_path):
    """
    Extracts key fields from a UPI screenshot using OCR (EasyOCR if available, else Tesseract):
      - amount: looks for ₹ or Rs followed by digits
      - upi_id: pattern \w+@\w+
      - txn_id: alphanumeric string of length 8–30
      - date: DD/MM/YYYY or similar
    Returns a dict:
      {'amount': str or None, 'upi_id': str or None, 'txn_id': str or None, 'date': str or None}
    """
    # Read and preprocess image for OCR
    img = cv2.imread(image_path)
    if img is None:
        return dict(amount=None, upi_id=None, txn_id=None, date=None)

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.medianBlur(gray, 3)
    # Use adaptive thresholding to improve text clarity
    thresh = cv2.adaptiveThreshold(gray, 255,
                                   cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
                                   cv2.THRESH_BINARY_INV, 11, 2)
    # Invert if necessary (so text is black on white)
    _, count_black = cv2.threshold(thresh, 128, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    if np.mean(count_black) < np.mean(thresh):
        thresh = cv2.bitwise_not(thresh)

    # OCR: EasyOCR if available, else Tesseract
    if _USE_EASYOCR:
        # EasyOCR returns a list of (bbox, text, confidence)
        results = _EASYOCR_READER.readtext(thresh, detail=0)
        text = "\n".join(results)
    else:
        # Tesseract config: LSTM only, assume single block of text
        config = '--oem 1 --psm 6'
        text = pytesseract.image_to_string(thresh, config=config)

    # Patterns for key fields
    amount_pattern = re.compile(r'₹\s*\d{1,7}(?:,\d{3})*(?:\.\d{1,2})?|\bRs\.?\s*\d{1,7}(?:,\d{3})*(?:\.\d{1,2})?\b')
    upi_pattern    = re.compile(r'\b[\w\.]+@[\w\.]+\b')
    txn_pattern    = re.compile(r'\b[A-Za-z0-9]{8,30}\b')
    date_pattern   = re.compile(r'\b(?:\d{1,2}[\/\-]\d{1,2}[\/\-]\d{2,4})\b')

    amount = None; upi_id = None; txn_id = None; date = None

    for line in text.split('\n'):
        if amount is None:
            m = amount_pattern.search(line)
            if m:
                candidate = m.group(0).replace(' ', '').replace('Rs.', '₹')
                # Validate numeric
                try:
                    numeric = float(candidate.replace('₹','').replace(',',''))
                    if numeric > 0:
                        amount = candidate
                except:
                    pass
        if upi_id is None:
            m = upi_pattern.search(line)
            if m:
                upi_id = m.group(0)
        if txn_id is None:
            m = txn_pattern.search(line)
            if m:
                txn_id = m.group(0)
        if date is None:
            m = date_pattern.search(line)
            if m:
                date = m.group(0)

    return dict(amount=amount, upi_id=upi_id, txn_id=txn_id, date=date)


def rule_check_fields(fields):
    """
    Given a dict of extracted fields, returns a consistency score in [0,1].
    There are 4 rules:
      1. amount: must match ^₹\d+(?:\.\d{1,2})?$
      2. upi_id: must match [\w\.]+@[\w\.]+
      3. txn_id: alphanumeric length 8–30
      4. date: valid DD/MM/YYYY and <= today
    Each passed rule adds 1; score = passed_count / 4.
    If any field is None, that rule fails.
    """
    score = 0
    total = 4

    # Rule 1: Amount
    amt = fields.get('amount')
    if amt:
        if re.match(r'^₹\d{1,7}(?:\.\d{1,2})?$', amt):
            try:
                if float(amt.replace('₹','').replace(',','')) > 0:
                    score += 1
            except:
                pass

    # Rule 2: UPI ID
    uid = fields.get('upi_id')
    if uid and re.match(r'^[\w\.]+@[\w\.]+$', uid):
        score += 1

    # Rule 3: Transaction ID
    tid = fields.get('txn_id')
    if tid and re.match(r'^[A-Za-z0-9]{8,30}$', tid):
        score += 1

    # Rule 4: Date
    dt = fields.get('date')
    if dt:
        # Normalize to DD/MM/YYYY
        dt_norm = dt.replace('-', '/')
        for fmt in ('%d/%m/%Y', '%d/%m/%y'):
            try:
                parsed = datetime.strptime(dt_norm, fmt)
                if parsed <= datetime.now():
                    score += 1
                break
            except:
                continue

    return score / total

# 12. Grad‐CAM Implementation
class GradCAM:
    def __init__(self, model, target_layer_name):
        """
        model: PyTorch model
        target_layer_name: name of the last conv layer (e.g., 'features.12')
        """
        self.model = model
        self.model.eval()
        self.gradient = None
        self.activation = None

        # Register hooks on target layer
        for name, module in self.model.named_modules():
            if name == target_layer_name:
                module.register_forward_hook(self.save_activation)
                module.register_backward_hook(self.save_gradient)

    def save_activation(self, module, input, output):
        self.activation = output.detach()

    def save_gradient(self, module, grad_input, grad_output):
        self.gradient = grad_output[0].detach()

    def __call__(self, input_tensor, class_idx=None):
        """
        input_tensor: single image tensor (1x3x224x224) on same device as model
        class_idx: index of class for which to compute Grad-CAM (0 = fake, 1 = real)
        """
        # Forward pass
        output = self.model(input_tensor)
        if class_idx is None:
            class_idx = output.argmax(dim=1).item()
        score = output[0, class_idx] if output.shape[-1] > 1 else output[0]

        # Backward to get gradients
        self.model.zero_grad()
        score.backward(retain_graph=True)

        grads = self.gradient  # [C, H, W]
        acts  = self.activation  # [C, H, W]

        # Global average pooling of gradients
        weights = grads.mean(dim=(1, 2), keepdim=True)  # [C,1,1]
        cam_map = (weights * acts).sum(dim=0)  # [H, W]
        cam_map = torch.relu(cam_map)
        cam_map -= cam_map.min()
        cam_map /= (cam_map.max() + 1e-8)
        cam_map = cam_map.cpu().numpy()
        return cam_map

# 13. Inference Pipeline (Hybrid)
def hybrid_inference(image_path, cnn_model, gradcam=None, weight=0.7, visualize=False):
    """
    Perform hybrid inference on a single screenshot:
      1) CNN visual tamper probability (p_cnn)
      2) OCR extract fields -> rule_score in [0,1], p_rules = 1 - rule_score
      3) final_score = weight * p_cnn + (1 - weight) * p_rules
    Returns dict with all scores and optionally shows Grad-CAM overlay.
    """
    # ---------- (A) CNN inference ----------
    img_pil = Image.open(image_path).convert('RGB')
    img_tensor = transform(img_pil).unsqueeze(0).to(device)
    cnn_model.eval()
    with torch.no_grad():
        p_cnn = cnn_model(img_tensor).item()  # Sigmoid output ∈ [0,1]

    # ---------- (B) OCR + Rule checks ----------
    fields = ocr_extract_fields(image_path)            # e.g. {'amount': '₹500', 'upi_id': 'abc@okbank', ...}
    rule_score = rule_check_fields(fields)             # ∈ [0,1], higher = more “valid”
    p_rules = 1.0 - rule_score                         # “probability of fake” by rule

    # ---------- (C) Late fusion ----------
    final_score = weight * p_cnn + (1.0 - weight) * p_rules
    label_pred = 'Fake' if final_score > 0.5 else 'Real'

    result = {
        'cnn_prob': p_cnn,
        'rule_score': rule_score,
        'ocr_fields': fields,
        'p_rules': p_rules,
        'final_score': final_score,
        'pred_label': label_pred
    }

    # ---------- (D) Grad-CAM visualization (robust) ----------
    if visualize and gradcam is not None:
        try:
            # 1) Generate raw CAM (float in [0,1])
            cam_map = gradcam(img_tensor, class_idx=0)    # class_idx=0 => “Fake” class

            # 2) Ensure it’s a float32 numpy array
            cam_map = cam_map.astype(np.float32)

            # 3) Resize CAM to (224, 224)
            cam_resized = cv2.resize(cam_map, (224, 224), interpolation=cv2.INTER_LINEAR)

            # 4) Normalize and convert to CV_8UC1 (uint8) with min=0, max=255
            cam_uint8 = cv2.normalize(
                cam_resized, None,
                alpha=0, beta=255,
                norm_type=cv2.NORM_MINMAX,
                dtype=cv2.CV_8U
            )  # Now cam_uint8 is single-channel 8-bit

            # 5) Apply JET colormap → heatmap (BGR, 8-bit)
            heatmap = cv2.applyColorMap(cam_uint8, cv2.COLORMAP_JET)

            # 6) Prepare original image as 224×224 BGR (uint8)
            orig_bgr = cv2.cvtColor(np.array(img_pil.resize((224, 224))), cv2.COLOR_RGB2BGR)

            # 7) Overlay heatmap on original (0.6:0.4 blend)
            overlay = cv2.addWeighted(orig_bgr, 0.6, heatmap, 0.4, 0)

            # 8) Display side by side
            plt.figure(figsize=(8, 4))
            plt.subplot(1, 2, 1)
            plt.imshow(cv2.cvtColor(orig_bgr, cv2.COLOR_BGR2RGB))
            plt.title('Original (224×224)')
            plt.axis('off')

            plt.subplot(1, 2, 2)
            plt.imshow(cv2.cvtColor(overlay, cv2.COLOR_BGR2RGB))
            plt.title('Grad-CAM Overlay')
            plt.axis('off')

            plt.show()

        except Exception as e:
            # If anything goes wrong (e.g. cam_map invalid), print warning and skip
            print(f"⚠️ Grad-CAM skipped due to error: {e}")

    return result


# 14. Loading Trained CNN Weights
def load_cnn_model(weights_path):
    """
    Instantiates a MobileNetV3-Small model, loads weights, and returns it on 'device'.
    """
    net = models.mobilenet_v3_small(pretrained=False)
    in_features = net.classifier[0].in_features
    net.classifier = nn.Sequential(
        nn.Linear(in_features, 128),
        nn.ReLU(),
        nn.Dropout(0.3),
        nn.Linear(128, 1),
        nn.Sigmoid()
    )
    net.load_state_dict(torch.load(weights_path, map_location=device))
    return net.to(device)

# 15. Example Usage on Held-Out Test Images (Revised)

if __name__ == "__main__":
    # (A) Load the trained CNN from disk
    cnn_weights_path = os.path.join(MODEL_DIR, 'upi_fake_detector_cnn.pth')
    if not os.path.exists(cnn_weights_path):
        raise FileNotFoundError(f"Cannot find weights at {cnn_weights_path}. Please train first.")
    cnn_model = load_cnn_model(cnn_weights_path)
    cnn_model.eval()

    # (B) Instantiate Grad-CAM on the last convolutional layer
    gradcam = GradCAM(cnn_model, target_layer_name='features.12')

    # (C) Check that TEST_DIR has images
    test_images = [f for f in os.listdir(TEST_DIR) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
    if not test_images:
        print(f"❗ No test images found in {TEST_DIR}. Please upload .jpg/.png files there.")
    else:
        print(f"🔍 Running inference on {len(test_images)} test image(s)...\n")

    # (D) Loop through each test image and run hybrid_inference
    for fname in test_images:
        img_path = os.path.join(TEST_DIR, fname)
        try:
            result = hybrid_inference(
                image_path=img_path,
                cnn_model=cnn_model,
                gradcam=gradcam,
                weight=0.7,            # 70% weight to CNN, 30% to rules
                visualize=True         # Shows Grad-CAM overlay
            )
        except Exception as e:
            print(f"Error processing {fname}: {e}")
            continue

        # Print the final verdict clearly
        print("========================================")
        print(f"File: {fname}")
        print("----------------------------------------")
        print(f"CNN Tamper Probability: {result['cnn_prob']:.4f}")
        print(f"OCR Extracted Fields: {result['ocr_fields']}")
        print(f"Rule-Based Consistency Score: {result['rule_score']:.4f}")
        print(f"Hybrid Final Score: {result['final_score']:.4f}")
        print(f">>> Predicted Label:  **{result['pred_label']}**")
        print("========================================\n")

from torchvision import models
model = models.mobilenet_v3_small(pretrained=True)
for name, module in model.named_modules():
    print(name)
